language: python
script:
 - python test.py

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run test.py

# Push the results back to codecov
after_success:
  - codecov
